language: bash
services: docker

env:
  - VERSION=8.36.0
  
install:
  - git clone https://github.com/manios/docker-multi-stage-rsyslog

before_script:
  - env | sort
  - image="manios/docker-multi-stage-rsyslog:$VERSION"

script:
  - travis_retry docker build -t "$image" .

after_script:
  - docker images
  - docker run -d --name myrsyslog "$image"
  - docker rm -f myrsyslog

# vim:set et ts=2 sw=2:

